# These are supported funding model platforms

github: naeruru
patreon: # Replace with a single Patreon username
ko_fi: naeruru
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
